name: Build and Deploy to Azure

on:
  push:
    branches:
      - '**'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: diabetespredictionregistry.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t diabetespredictionregistry.azurecr.io/ml-webapp:latest .
          docker push diabetespredictionregistry.azurecr.io/ml-webapp:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'diabetesprediction-webapp'
          images: 'diabetespredictionregistry.azurecr.io/ml-webapp:latest'
